import { useWeb3 } from '@3rdweb/hooks';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import Header from '../components/Header';
import Hero from '../components/Hero';
import { client } from '../lib/sanityClient';
import toast, { Toaster } from 'react-hot-toast';

const Home: NextPage = () => {
  const { address, connectWallet } = useWeb3();
  const welcomeUser = (userName: string, toasterHandler = toast) => {
    toasterHandler.success(
      `Welcome back ${userName !== 'Unnamed ' ? userName : ''}!`,
      {
        style: {
          background: '#04111d',
          color: '#fff',
        },
      }
    );
  };

  useEffect(() => {
    if (!address) return;
    (async () => {
      const userDoc = {
        _type: 'users',
        _id: address,
        userName: 'Unnamed',
        walletAddress: address,
      };

      const result = await client.createIfNotExists(userDoc);
      welcomeUser(result.userName);
    })();
  }, [address]);

  return (
    <div className='overflow-hidden'>
      <Toaster position='top-center' reverseOrder={false} />
      {address ? (
        <>
          <Head>
            <title>Opensea</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <Header />
          <Hero />
        </>
      ) : (
        <div className='flex flex-col justify-center items-center h-screen w-screen bg-[#3b3d42]'>
          <Head>
            <title>Connect Wallet</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>
          <button
            className='border border-[#282b2f] bg-[#2081e2] p-[0.8rem] text-xl font-semibold rounded-lg cursor-pointer text-black'
            onClick={() => connectWallet('injected')}
          >
            Connect Wallet
          </button>
          <div className='text-lg text-center text=[#282b2f] font-semibold mt-4'>
            You need Chrome to be <br /> able to run this app
          </div>
        </div>
      )}
    </div>
  );
};

export default Home;
